// string_table_id.h

#pragma once


// -----------------------------------------------------------------------
// main frame
// ----------------
// menu
#define RSID_STR_MAIN_MENU_FILE       40021
#define RSID_STR_MAIN_MENU_FILE_CLOSE 40022

#define RSID_STR_MAIN_MENU_VIEW                    40041
#define RSID_STR_MAIN_MENU_VIEW_AUTO_DISPLAY_CELLS 40042
#define RSID_STR_MAIN_MENU_VIEW_COLUMN_GROUP       40043
#define RSID_STR_MAIN_MENU_VIEW_DISPLAY_CELLS      40044
#define RSID_STR_MAIN_MENU_VIEW_RELOAD             40045

#define RSID_STR_MAIN_MENU_EDIT                           40061
#define RSID_STR_MAIN_MENU_EDIT_EDIT_COMMON_PARAMETER     40062
#define RSID_STR_MAIN_MENU_EDIT_ADD_ENTRY                 40063
#define RSID_STR_MAIN_MENU_EDIT_DELETE_ENTRY              40064
#define RSID_STR_MAIN_MENU_EDIT_DELETE_ALL_ENTRY          40065
#define RSID_STR_MAIN_MENU_EDIT_SHOW_PROPERTY_OF_ENTRY    40066
#define RSID_STR_MAIN_MENU_EDIT_EDIT_INDIVIDUAL_PARAMETER 40067

#define RSID_STR_MAIN_MENU_CONVERT                 40081
#define RSID_STR_MAIN_MENU_CONVERT_CONVERT_ONE_BMS 40082
#define RSID_STR_MAIN_MENU_CONVERT_CONVERT_ALL_BMS 40083

#define RSID_STR_MAIN_MENU_TOOL                             40101
#define RSID_STR_MAIN_MENU_TOOL_SETTINGS                    40102
#define RSID_STR_MAIN_MENU_TOOL_RELOAD_SQUIRREL_SCRIPT      40103
#define RSID_STR_MAIN_MENU_TOOL_SHOW_SQUIRREL_OUTPUT_DIALOG 40104
#define RSID_STR_MAIN_MENU_TOOL_START_SEARCHER              40105

#define RSID_STR_MAIN_MENU_HELP                     40121
#define RSID_STR_MAIN_MENU_HELP_VERSION_INFORMATION 40122

// ----------------
// tool bar
#define RSID_STR_MAIN_TB_AUTO_DISPLAY_CELLS          40201
#define RSID_STR_MAIN_TB_SELECT_COLUMN_LABEL         40202
#define RSID_STR_MAIN_TB_DISPLAY_CELLS               40203
#define RSID_STR_MAIN_TB_RELOAD                      40204
#define RSID_STR_MAIN_TB_EDIT_COMMON_PARAMETER       40205
#define RSID_STR_MAIN_TB_ADD_ENTRY                   40206
#define RSID_STR_MAIN_TB_DELETE_ENTRY                40207
#define RSID_STR_MAIN_TB_DELETE_ALL_ENTRY            40208
#define RSID_STR_MAIN_TB_SHOW_PROPERTY_OF_ENTRY      40209
#define RSID_STR_MAIN_TB_EDIT_INDIVIDUAL_PARAMETER   40210
#define RSID_STR_MAIN_TB_CONVERT_ONE_BMS             40211
#define RSID_STR_MAIN_TB_CONVERT_ALL_BMS             40212
#define RSID_STR_MAIN_TB_RELOAD_SQUIRREL_SCRIPT      40213
#define RSID_STR_MAIN_TB_SHOW_SQUIRREL_OUTPUT_DIALOG 40214
#define RSID_STR_MAIN_TB_START_SEARCHER              40215

// ----------------
// popup entry menu
#define RSID_STR_MAIN_PO_ENTRY_SHOW_PROPERTY_OF_ENTRY    40301
#define RSID_STR_MAIN_PO_ENTRY_EDIT_INDIVIDUAL_PARAMETER 40302
#define RSID_STR_MAIN_PO_ENTRY_CONVERT_ONE_BMS           40303
#define RSID_STR_MAIN_PO_ENTRY_DELETE_ENTRY              40304
#define RSID_STR_MAIN_PO_ENTRY_PROCESSOR_MENU            40305

// Searcher Œ“—p
#define RSID_STR_MAIN_PO_ENTRY_PROCESSOR_MENU_PLAY_PREVIEW    40371
#define RSID_STR_MAIN_PO_ENTRY_PROCESSOR_MENU_OPEN            40372
#define RSID_STR_MAIN_PO_ENTRY_PROCESSOR_MENU_OPEN_BY_NOTEPAD 40373
#define RSID_STR_MAIN_PO_ENTRY_PROCESSOR_MENU_FILE_OPERATIONS 40374

// ----------------
// column name (use at script)
#define RSID_STR_MAIN_COLUMN_NAME_OBJECT_COUNT               40601
#define RSID_STR_MAIN_COLUMN_NAME_OBJECT_OF_1P_COUNT         40602
#define RSID_STR_MAIN_COLUMN_NAME_OBJECT_OF_2P_COUNT         40603
#define RSID_STR_MAIN_COLUMN_NAME_MOST_SERIOUS_ERROR         40604
#define RSID_STR_MAIN_COLUMN_NAME_RANDOM_STATEMENT           40605
#define RSID_STR_MAIN_COLUMN_NAME_RANDOM_STATEMENT_EXIST     40606
#define RSID_STR_MAIN_COLUMN_NAME_RANDOM_STATEMENT_NOT_EXIST 40607
#define RSID_STR_MAIN_COLUMN_NAME_FULL_PATH                  40608
#define RSID_STR_MAIN_COLUMN_NAME_BASENAME                   40609
#define RSID_STR_MAIN_COLUMN_NAME_PARENT_DIRECTORY           40610
#define RSID_STR_MAIN_COLUMN_NAME_PARENTS_PARENT_DIRECTORY   40611
#define RSID_STR_MAIN_COLUMN_NAME_PLAYING_TIME               40612

#define RSID_STR_MAIN_COLUMN_NAME_PARAMETER                  40613
#define RSID_STR_MAIN_COLUMN_NAME_PARAMETER_INDIVIDUAL       40614
#define RSID_STR_MAIN_COLUMN_NAME_PARAMETER_COMMON           40615

// column group name (use at script)
// Searcher Œ“—p
#define RSID_STR_MAIN_COLUMN_GROUP_NAME_SIMPLE     40671
#define RSID_STR_MAIN_COLUMN_GROUP_NAME_DETAILS    40672
#define RSID_STR_MAIN_COLUMN_GROUP_NAME_VARIOUS    40673
#define RSID_STR_MAIN_COLUMN_GROUP_NAME_FOR_SEARCH 40674

// ----------------
// main frame
#define RSID_STR_MAIN_MB_SCRIPT_ERROR_CAP                           40701
#define RSID_STR_MAIN_MB_SCRIPT_ERROR_MSG                           40702
#define RSID_STR_MAIN_SQUIRREL_STANDARD_OUTPUT_DIALOG_TITLE         40703
#define RSID_STR_MAIN_DEFAULT_SORT_METHOD_NAME                      40704
#define RSID_STR_MAIN_STATUS_BAR_SORT_METHOD_TITLE                  40705
#define RSID_STR_MAIN_DEFAULT_FIRST_COLUMN_NAME                     40706
#define RSID_STR_MAIN_STATUS_BAR_SORT_METHOD_DESCENDING             40707
#define RSID_STR_MAIN_ADD_ENTRY_FILE_DIALOG_BMS_BME_FILE            40708
#define RSID_STR_MAIN_ADD_ENTRY_FILE_DIALOG_ALL_FILE                40709
#define RSID_STR_MAIN_MB_DELETE_ALL_ENTRY_CAUTION_CAP               40710
#define RSID_STR_MAIN_MB_DELETE_ALL_ENTRY_CAUTION_MSG               40711
#define RSID_STR_MAIN_MB_EDIT_INDIVIDUAL_PARAMETER_COPY_CAUTION_CAP 40712
#define RSID_STR_MAIN_MB_EDIT_INDIVIDUAL_PARAMETER_COPY_CAUTION_MSG 40713
#define RSID_STR_MAIN_MB_START_SEARCHER_ERROR_CAP                   40714
#define RSID_STR_MAIN_MB_START_SEARCHER_ERROR_MSG                   40715
#define RSID_STR_MAIN_ENTRY_PROCESSOR_MENU_EMPTY                    40716

// -----------------------------------------------------------------------
// settings
// reserve 41000

// -----------------------------------------------------------------------
// parameter property sheet
#define RSID_STR_PPS_TITLE 41501

#define RSID_STR_PPS_GENERAL                      41551
#define RSID_STR_PPS_GENERAL_LOAD_SAVE_GROUP      41552
#define RSID_STR_PPS_GENERAL_LOAD_BUTTON          41553
#define RSID_STR_PPS_GENERAL_SAVE_BUTTON          41554
#define RSID_STR_PPS_GENERAL_NAME_LABEL           41555
#define RSID_STR_PPS_GENERAL_USE_SCRIPT_CHECK     41556
#define RSID_STR_PPS_GENERAL_SCRIPT_LABEL         41557
#define RSID_STR_PPS_GENERAL_SCRIPT_REF_BUTTON    41558
#define RSID_STR_PPS_GENERAL_OUTPUT_LOG_CHECK     41559
#define RSID_STR_PPS_GENERAL_LOG_LABEL            41560
#define RSID_STR_PPS_GENERAL_LOG_REF_BUTTON       41561
#define RSID_STR_PPS_GENERAL_FILE_DIALOG_ALL_FILE 41562

#define RSID_STR_PPS_OUTPUT                            41601
#define RSID_STR_PPS_OUTPUT_OUTPUT_AS_OGG_CHECK        41602
#define RSID_STR_PPS_OUTPUT_OGG_BASE_QUALITY_LABEL     41603
#define RSID_STR_PPS_OUTPUT_NEVER_OVERWRITE_CHECK      41604
#define RSID_STR_PPS_OUTPUT_REMOVE_CHAR_CHECK          41605
#define RSID_STR_PPS_OUTPUT_OUTPUT_FILE_TEMPLATE_LABEL 41606
#define RSID_STR_PPS_OUTPUT_OUTPUT_FILE_HELP_BUTTON    41607
#define RSID_STR_PPS_OUTPUT_MB_OGG_BASE_QUALITY_CAP    41608
#define RSID_STR_PPS_OUTPUT_MB_OGG_BASE_QUALITY_MSG    41609

#define RSID_STR_PPS_PARSER                                41651
#define RSID_STR_PPS_PARSER_IGNORE_BGA_CHANNEL_CHECK       41652
#define RSID_STR_PPS_PARSER_NOT_NESTING_IF_STATEMENT_CHECK 41653

#define RSID_STR_PPS_MIXIN                                    41701
#define RSID_STR_PPS_MIXIN_CANCEL_AT_RESOUNDING_CHECK         41702
#define RSID_STR_PPS_MIXIN_START_LABEL                        41703
#define RSID_STR_PPS_MIXIN_END_LABEL                          41704
#define RSID_STR_PPS_MIXIN_CONVERT_START_END_BAR_NUMBER_LABEL 41705
#define RSID_STR_PPS_MIXIN_DO_TRIMING_CHECK                   41706
#define RSID_STR_PPS_MIXIN_REMOVE_FRONT_SILENCE_CHECK         41707
#define RSID_STR_PPS_MIXIN_INSERT_FRONT_SILENCE_CHECK         41708
#define RSID_STR_PPS_MIXIN_INSERT_FRONT_SILENCE_SECOND_LABEL  41709
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_CAP                 41710
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_MSG_START           41711
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_MSG_END             41712
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_MSG_ORDER           41713
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_MSG_TRIM_START      41714
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_MSG_TRIM_END        41715
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_MSG_TRIM_ORDER      41716
#define RSID_STR_PPS_MIXIN_MB_KILL_ACTIVE_MSG_FRONT_SILENCE   41717

#define RSID_STR_PPS_AUDIO                               41751
#define RSID_STR_PPS_AUDIO_NORMALIZE_KIND_NONE_RADIO     41752
#define RSID_STR_PPS_AUDIO_NORMALIZE_KIND_PEAK_RADIO     41753
#define RSID_STR_PPS_AUDIO_NORMALIZE_KIND_AVERAGE_RADIO  41754
#define RSID_STR_PPS_AUDIO_NORMALIZE_KIND_OVER_RADIO     41755
#define RSID_STR_PPS_AUDIO_NORMALIZE_KIND_GROUP          41756
#define RSID_STR_PPS_AUDIO_NORMALIZE_OVER_PPM_LABEL      41757
#define RSID_STR_PPS_AUDIO_VOLUME_LABEL                  41758
#define RSID_STR_PPS_AUDIO_MB_KILL_ACTIVE_CAP            41759
#define RSID_STR_PPS_AUDIO_MB_KILL_ACTIVE_MSG_OVER_PPM   41760
#define RSID_STR_PPS_AUDIO_MB_KILL_ACTIVE_MSG_VOLUME     41761

#define RSID_STR_PPS_AFTER_PROCESS                             41801
#define RSID_STR_PPS_AFTER_PROCESS_EXECUTE_AFTER_PROCESS_CHECK 41802
#define RSID_STR_PPS_AFTER_PROCESS_EXECUTE_FILE_LABEL          41803
#define RSID_STR_PPS_AFTER_PROCESS_EXECUTE_FILE_REF_BUTTON     41804
#define RSID_STR_PPS_AFTER_PROCESS_EXECUTE_ARGUMENTS_LABEL     41805
#define RSID_STR_PPS_AFTER_PROCESS_EXECUTE_ARGUMENTS_HELP      41806
#define RSID_STR_PPS_AFTER_PROCESS_START_ON_BACKGROUND_CHECK   41807
#define RSID_STR_PPS_AFTER_PROCESS_WAIT_FOR_PROCESS_EXIT_CHECK 41808
#define RSID_STR_PPS_AFTER_PROCESS_DELETE_OUTPUT_FILE_CHECK    41809
#define RSID_STR_PPS_AFTER_PROCESS_FILE_DIALOG_EXE_FILE        41810
#define RSID_STR_PPS_AFTER_PROCESS_FILE_DIALOG_ALL_FILE        41811

// -----------------------------------------------------------------------
// convert dialog
#define RSID_STR_CONVERT_TITLE                   42001

#define RSID_STR_CONVERT_ABORT_BUTTON            42011
#define RSID_STR_CONVERT_INITIALIZE_TITLE_LABEL  42012
#define RSID_STR_CONVERT_INITIALIZE_REPORT_LABEL 42013
#define RSID_STR_CONVERT_PARSE_TITLE_LABEL       42014
#define RSID_STR_CONVERT_PARSE_REPORT_LABEL      42015
#define RSID_STR_CONVERT_WAV_TITLE_LABEL         42016
#define RSID_STR_CONVERT_WAV_REPORT_LABEL        42017
#define RSID_STR_CONVERT_MIXIN_TITLE_LABEL       42018
#define RSID_STR_CONVERT_MIXIN_REPORT_LABEL      42019
#define RSID_STR_CONVERT_AFTER_TITLE_LABEL       42020
#define RSID_STR_CONVERT_AFTER_REPORT_LABEL      42021
#define RSID_STR_CONVERT_PLAY_WAV_BUTTON         42022
#define RSID_STR_CONVERT_STOP_WAV_BUTTON         42023
#define RSID_STR_CONVERT_SAVE_AS_WAV_BUTTON      42024
#define RSID_STR_CONVERT_SAVE_AS_OGG_BUTTON      42025
#define RSID_STR_CONVERT_OPEN_WAV_BUTTON         42026
#define RSID_STR_CONVERT_SHOW_OUTPUT_BOX_BUTTON  42027

#define RSID_STR_CONVERT_FILE_DIALOG_WAV_FILE 42051
#define RSID_STR_CONVERT_FILE_DIALOG_OGG_FILE 42052
#define RSID_STR_CONVERT_FILE_DIALOG_ALL_FILE 42053
#define RSID_STR_CONVERT_MB_OPEN_WAV_CAP      42054
#define RSID_STR_CONVERT_MB_OPEN_WAV_MSG      42055
#define RSID_STR_CONVERT_OUTPUT_DIALOG_TITLE  42056
#define RSID_STR_CONVERT_OPEN_LOG_ERROR_MSG   42057
#define RSID_STR_CONVERT_OUTPUT_TO_LOG_ERROR  42058

#define RSID_STR_CONVERT_MB_ERROR_ABORT_CAP        42101
#define RSID_STR_CONVERT_MB_ERROR_ABORT_MSG        42102
#define RSID_STR_CONVERT_MB_ERROR_MEMORY_CAP       42103
#define RSID_STR_CONVERT_MB_ERROR_MEMORY_MSG       42104
#define RSID_STR_CONVERT_MB_ERROR_UNEXPECTED_CAP   42105
#define RSID_STR_CONVERT_MB_ERROR_UNEXPECTED_MSG   42106
#define RSID_STR_CONVERT_MB_ERROR_SCRIPT_CAP       42107
#define RSID_STR_CONVERT_MB_ERROR_SCRIPT_MSG       42108
#define RSID_STR_CONVERT_MB_INFO_RANDOM_DIALOG_CAP 42109
#define RSID_STR_CONVERT_MB_INFO_RANDOM_DIALOG_MSG 42110

#define RSID_STR_CONVERT_REPORT_LABEL_COMPLETED                       42151
#define RSID_STR_CONVERT_REPORT_LABEL_ERROR_EXIST                     42152
#define RSID_STR_CONVERT_REPORT_LABEL_ABORT                           42153
#define RSID_STR_CONVERT_REPORT_RESULT_ABORT                          42154
#define RSID_STR_CONVERT_REPORT_LABEL_INITIALIZE_RUNNING              42155
#define RSID_STR_CONVERT_REPORT_RESULT_INITIALIZE_RUNNING             42156
#define RSID_STR_CONVERT_REPORT_LABEL_PARSE_RUNNING                   42157
#define RSID_STR_CONVERT_REPORT_RESULT_PARSE_RUNNING                  42158
#define RSID_STR_CONVERT_REPORT_LABEL_READ_AUDIO_FILES_RUNNING        42159
#define RSID_STR_CONVERT_REPORT_RESULT_READ_AUDIO_FILES_RUNNING       42160
#define RSID_STR_CONVERT_REPORT_LABEL_ONE_AUDIO_FILE_READ_RUNNING     42161
#define RSID_STR_CONVERT_REPORT_LABEL_MIXIN_RUNNING                   42162
#define RSID_STR_CONVERT_REPORT_RESULT_MIXIN_RUNNING                  42163
#define RSID_STR_CONVERT_REPORT_LABEL_AFFECT_WAVE_RUNNING             42164
#define RSID_STR_CONVERT_REPORT_RESULT_AFFECT_WAVE_RUNNING            42165
#define RSID_STR_CONVERT_REPORT_RESULT_OUTPUT_TO_FILE_RUNNING         42166
#define RSID_STR_CONVERT_REPORT_LABEL_AFTER_OUTPUT_TO_FILE_NO_OUTPUT  42167
#define RSID_STR_CONVERT_REPORT_RESULT_AFTER_OUTPUT_TO_FILE_COMPLETED 42168

// -----------------------------------------------------------------------
// multiple convert dialog
#define RSID_STR_MULTIPLE_TITLE                           42201
#define RSID_STR_MULTIPLE_MENU_SHOW_LOG                   42202
#define RSID_STR_MULTIPLE_ABORT_BUTTON                    42203
#define RSID_STR_MULTIPLE_COLUMN_BMS                      42204
#define RSID_STR_MULTIPLE_COLUMN_RESULT                   42205
#define RSID_STR_MULTIPLE_COLUMN_MOST_SERIOUS_ERROR       42206
#define RSID_STR_MULTIPLE_COLUMN_DEFAULT_TEXT_UNCONVERTED 42207
#define RSID_STR_MULTIPLE_LOG_DIALOG_TITLE                42208
#define RSID_STR_MULTIPLE_STATUS_TEXT_CONVERTING          42209
#define RSID_STR_MULTIPLE_STATUS_TEXT_ABORTED             42210
#define RSID_STR_MULTIPLE_STATUS_TEXT_COMPLETED           42211

// -----------------------------------------------------------------------
// entry dialog
#define RSID_STR_EMTRY_TITLE                            42301
#define RSID_STR_EMTRY_USING_PARAMETER_TITLE_LABEL      42302
#define RSID_STR_EMTRY_USE_COMMON_PARAMETER_BUTTON      42303
#define RSID_STR_EMTRY_USE_INDIVIDUAL_PARAMETER_BUTTON  42304
#define RSID_STR_EMTRY_CONVERT_BUTTON                   42305
#define RSID_STR_EMTRY_COLUMN_NAME                      42306
#define RSID_STR_EMTRY_COLUMN_VALUE                     42307
#define RSID_STR_EMTRY_USING_PARAMETER_LABEL_COMMON     42308
#define RSID_STR_EMTRY_USING_PARAMETER_LABEL_INDIVIDUAL 42309
#define RSID_STR_EMTRY_MB_USE_COMMON_CAP                42310
#define RSID_STR_EMTRY_MB_USE_COMMON_MSG                42311
#define RSID_STR_EMTRY_MB_USE_INDIVIDUAL_CAP            42312
#define RSID_STR_EMTRY_MB_USE_INDIVIDUAL_MSG            42313

// -----------------------------------------------------------------------
// random statement dialog
#define RSID_STR_RANDOM_TITLE        42351
#define RSID_STR_RANDOM_CHECK_BUTTON 42352
#define RSID_STR_RANDOM_OK_BUTTON    42353

// -----------------------------------------------------------------------
// template path translate help dialog
#define RSID_STR_TEMPLATE_PATH_TITLE                                         42401
#define RSID_STR_TEMPLATE_PATH_MENU_COPY                                     42402
#define RSID_STR_TEMPLATE_PATH_COLUMN_NAME                                   42403
#define RSID_STR_TEMPLATE_PATH_COLUMN_DESCRIPTION                            42404
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_PATH                           42405
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_PATH_WITHOUT_EXTENSION         42406
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_DIRECTORY                      42407
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_PARENT_DIRECTORY               42408
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_BASENAME                       42409
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_BASENAME_WITHOUT_EXTENSION     42410
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_AUTO_EXTENSION_CHANGE          42411
#define RSID_STR_TEMPLATE_PATH_TEXT_INPUT_BMS_BASENAME_AUTO_EXTENSION_CHANGE 42412
#define RSID_STR_TEMPLATE_PATH_TEXT_AUTO_EXTENSION                           42413
#define RSID_STR_TEMPLATE_PATH_TEXT_BMX2WAV_DIRECTORY                        42414
#define RSID_STR_TEMPLATE_PATH_TEXT_HEADER_XXXXX                             42415


// -----------------------------------------------------------------------
// ===== searcher =====
// -----------------------------------------------------------------------
// main frame
// ----------------
// searcher main menu
#define RSID_STR_SRC_MAIN_FILE          46011
#define RSID_STR_SRC_MAIN_FILE_CLOSE    46012

#define RSID_STR_SRC_MAIN_TOOL          46061
#define RSID_STR_SRC_MAIN_TOOL_SETTINGS 46062

// ----------------
// searcher tree menu
#define RSID_STR_SRC_MAIN_PO_TREE_OPEN_DIRECTORY 46101

// ----------------
// searcher entry menu
#define RSID_STR_SRC_MAIN_PO_ENTRY_HIDE_ENTRY     46121
#define RSID_STR_SRC_MAIN_PO_ENTRY_PROCESSOR_MENU 46122

// ----------------
// searcher tool bar
#define RSID_STR_SRC_MAIN_TB_RELOAD_SQUIRREL_SCRIPT      46201
#define RSID_STR_SRC_MAIN_TB_SHOW_SQUIRREL_OUTPUT_DIALOG 46202
#define RSID_STR_SRC_MAIN_TB_FILTER_LABEL                46203
#define RSID_STR_SRC_MAIN_TB_AUTO_DISPLAY_CELLS          46204
#define RSID_STR_SRC_MAIN_TB_SELECT_COLUMN_LABEL         46205
#define RSID_STR_SRC_MAIN_TB_DISPLAY_CELLS               46206
#define RSID_STR_SRC_MAIN_TB_EXECUTE_SEARCH_LABEL        46207
#define RSID_STR_SRC_MAIN_TB_EXECUTE_SEARCH              46208

// display filter (use at script)
#define RSID_STR_SRC_MAIN_TB_DISPLAY_FILTER_ALL_PASS    46261
#define RSID_STR_SRC_MAIN_TB_DISPLAY_FILTER_BMS_GENERAL 46262
#define RSID_STR_SRC_MAIN_TB_DISPLAY_FILTER_ONLY_BMS    46263
#define RSID_STR_SRC_MAIN_TB_DISPLAY_FILTER_ONLY_BME    46264

// search method (use at script)
#define RSID_STR_SRC_MAIN_TB_SEARCH_METHOD_BMS_ALL            46281
#define RSID_STR_SRC_MAIN_TB_SEARCH_METHOD_FILTER_BMS_GENERAL 46282
#define RSID_STR_SRC_MAIN_TB_SEARCH_METHOD_MOST_PLAYLEVEL     46283

// ----------------
// searcher main frame
#define RSID_STR_SRC_MAIN_MB_SCRIPT_ERROR_CAP                        46301
#define RSID_STR_SRC_MAIN_MB_SCRIPT_ERROR_MSG                        46302
#define RSID_STR_SRC_MAIN_SQUIRREL_STANDARD_OUTPUT_DIALOG_TITLE      46303
#define RSID_STR_SRC_MAIN_DEFAULT_SORT_METHOD_NAME                   46304
#define RSID_STR_SRC_MAIN_STATUS_BAR_SORT_METHOD_TITLE               46305
#define RSID_STR_SRC_MAIN_ENTRY_PROCESSOR_MENU_EMPTY                 46306
#define RSID_STR_SRC_MAIN_STATUS_BAR_SORT_METHOD_DESCENDING          46307
#define RSID_STR_SRC_MAIN_DEFAULT_FIRST_COLUMN_NAME                  46001
#define RSID_STR_SRC_MAIN_MB_EXECUTE_SEARCH_IMPOSSIBLE_DIRECTORY_CAP 46308
#define RSID_STR_SRC_MAIN_MB_EXECUTE_SEARCH_IMPOSSIBLE_DIRECTORY_MSG 46309
#define RSID_STR_SRC_MAIN_MB_EXECUTE_SEARCH_EXECUTE_CONFIRM_CAP      46310
#define RSID_STR_SRC_MAIN_MB_EXECUTE_SEARCH_EXECUTE_CONFIRM_MSG      46311
#define RSID_STR_SRC_MAIN_MB_SEARCH_RESULT_DESTRUCTION_CONFIRM_CAP   46312
#define RSID_STR_SRC_MAIN_MB_SEARCH_RESULT_DESTRUCTION_CONFIRM_MSG   46313

// -----------------------------------------------------------------------
// searcher settings property sheet
#define RSID_STR_SRC_SPS_TITLE 46401

#define RSID_STR_SRC_SPS_SETTINGS                                    46451
#define RSID_STR_SRC_SPS_SETTINGS_HOME_LABEL                         46452
#define RSID_STR_SRC_SPS_SETTINGS_HOME_REF_BUTTON                    46453
#define RSID_STR_SRC_SPS_SETTINGS_AUTO_DISPLAY_CHECK                 46454
#define RSID_STR_SRC_SPS_SETTINGS_ASYNCHRONOUS_CHECK                 46455
#define RSID_STR_SRC_SPS_SETTINGS_HOME_REF_FOLDER_DIALOG_DESCRIPTION 46456

// -----------------------------------------------------------------------
// searcher entry wait dialog
#define RSID_STR_SRC_ENTRY_WAIT_DIALOG_TITLE 46801
#define RSID_STR_SRC_ENTRY_WAIT_DIALOG_TEXT  46802



// -----------------------------------------------------------------------
// 50000
// message
// ----------------
// main
#define RSID_STR_MSG_INTERNAL_ERROR                   50001
#define RSID_STR_MSG_UNEXPECTED_ERROR                 50011
#define RSID_STR_MSG_UNEXPECTED_ERROR_CAP             50012
#define RSID_STR_MSG_COMMAND_LINE_ERROR               50013
#define RSID_STR_MSG_COMMAND_LINE_ERROR_CAP           50014

// ----------------
// convert
#define RSID_STR_MSG_ENTRIED_AUDIO_FILE_NOT_FOUND     50031
#define RSID_STR_MSG_AUDIO_FILE_OPEN_ERROR            50032
#define RSID_STR_MSG_WAV_FILE_READ_ERROR              50033
#define RSID_STR_MSG_WAV_FILE_WRITE_ERROR             50034
#define RSID_STR_MSG_OGG_FILE_OPEN_ERROR              50035
#define RSID_STR_MSG_OGG_FILE_READ_ERROR              50036
#define RSID_STR_MSG_INVALID_WAV_FILE_FORMAT          50037
#define RSID_STR_MSG_UNSUPPORTED_WAV_FILE_FORMAT      50038
#define RSID_STR_MSG_BAD_ALLOCATION                   50039
#define RSID_STR_MSG_BMS_FILE_ACCESS_ERROR            50040
#define RSID_STR_MSG_OUTPUT_FILE_IS_INPUT_FILE_PATH   50041
#define RSID_STR_MSG_INVALID_FORMAT_AS_BPM_HEADER     50042
#define RSID_STR_MSG_INVALID_FORMAT_AS_EXTENDED_BPM   50043
#define RSID_STR_MSG_INVALID_FORMAT_AS_STOP_SEQUENCE  50044
#define RSID_STR_MSG_INVALID_FORMAT_AS_LNOBJ_HEADER   50045
#define RSID_STR_MSG_LN_OBJECT_INVALID_ENCLOSE        50046
#define RSID_STR_MSG_LN_OBJECT_INVALID_ENCLOSE_ADD    50047
#define RSID_STR_MSG_LN_OBJECT_NOT_ENCLOSED           50048
#define RSID_STR_MSG_NOT_ENTRIED_WAV_WAS_USED         50049
#define RSID_STR_MSG_INVALID_FORMAT_AS_BPM_CHANGE     50050
#define RSID_STR_MSG_EX_BPM_CHANGE_ENTRY_NOT_EXIST    50051
#define RSID_STR_MSG_STOP_SEQUENCE_ENTRY_NOT_EXIST    50052
#define RSID_STR_MSG_OUTPUT_FILE_ACCESS_ERROR         50053

// ----------------
// base
#define RSID_STR_MSG_INVALID_CHAR_USED_AS_WORD      50301
#define RSID_STR_MSG_INVALID_WORD_VALUE_USED        50302
#define RSID_STR_MSG_BUFFER_OUT_OF_RANGE_ACCESS     50303
#define RSID_STR_MSG_REQIORED_RESOLUTION_IS_TOO_BIG 50304
// parser
#define RSID_STR_MSG_P_FILE_ACCESS_ERROR                50311
#define RSID_STR_MSG_P_NO_BEGINNING_END_RAMDOM          50312
#define RSID_STR_MSG_P_HEADER_COLLISION                 50313
#define RSID_STR_MSG_P_INVALID_BPM                      50314
#define RSID_STR_MSG_P_INVALID_LNOBJ                    50315
#define RSID_STR_MSG_P_OBJECT_COLLISION                 50316
#define RSID_STR_MSG_P_BAR_LENGTH_CHANGE_COLLISION      50317
#define RSID_STR_MSG_P_INVALID_CHANNEL_OR_HEADER_SYNTAX 50318
#define RSID_STR_MSG_P_CORRESPONDING_END_IF_IS_NOTING   50319
#define RSID_STR_MSG_P_INVALID_RANDOM_STATEMENT_VALUE   50320
#define RSID_STR_MSG_P_CORRESPONDING_IF_IS_NOTIONG      50321
#define RSID_STR_MSG_P_INVALID_BAR_LENGTH_CHANGE_VALUE  50322
#define RSID_STR_MSG_P_INVALID_OBJECT_EXPRESSION        50323
#define RSID_STR_MSG_P_INVALID_EXTENDED_BPM             50324
#define RSID_STR_MSG_P_INVALID_STOP_SEQUENCE            50325
#define RSID_STR_MSG_P_UNDEFINED_OBJECT_USED            50326
#define RSID_STR_MSG_P_DEFINED_OBJECT_NOT_USED          50327
#define RSID_STR_MSG_P_RESOLUTION_EXCEEDED_LIMIT        50328

// ----------------
// core
// converter
#define RSID_STR_MSG_C_USED_MEMORY_EXCEEDED_LIMIT                  50511
#define RSID_STR_MSG_C_USE_DEFAULT_BPM                             50512
#define RSID_STR_MSG_C_USE_DEFAULT_BPM_NO_SPECIFIED                50513
#define RSID_STR_MSG_C_TREAT_EXTENDED_BPM_AS_NOT_SPECIFIED         50514
#define RSID_STR_MSG_C_TREAT_STOP_SEQUENCE_AS_NOT_SPECIFIED        50515
#define RSID_STR_MSG_C_DECIMAL_IS_SPECIFIED_AS_STOP_SEQUENCE       50516
#define RSID_STR_MSG_C_TREAT_LNOBJ_AS_NOT_SPECIFIED                50517
#define RSID_STR_MSG_C_TREAT_WAV_AS_NOT_SPECIFIED                  50518
#define RSID_STR_MSG_C_TREAT_EMPTY_FILE_AS_SPECIFIED_AS_WAV        50519
#define RSID_STR_MSG_C_TREAT_BPM_AS_NOT_CHANGED_WITH_NUMBER        50520
#define RSID_STR_MSG_C_TREAT_BPM_AS_NOT_CHANGED_WITH_NUMBER_OBJECT 50521
#define RSID_STR_MSG_C_TREAT_STOP_SEQUENCE_AS_NOTHING              50522

// use at script
#define RSID_STR_MSG_C_ABORTED                         50701
#define RSID_STR_MSG_C_REQUEST_TO_ABORT_BY_USER        50702
#define RSID_STR_MSG_C_EXCEPTION_OCCURRED_ERROR_EXIST  50703
#define RSID_STR_MSG_C_CONVERT_START                   50704
#define RSID_STR_MSG_C_INITIALIZE_START                50705
#define RSID_STR_MSG_C_INITIALIZE_END                  50706
#define RSID_STR_MSG_C_PARSE_START                     50707
#define RSID_STR_MSG_C_PARSE_END                       50708
#define RSID_STR_MSG_C_MAX_RESOLUTION_AND_BAR_NUMBER   50709
#define RSID_STR_MSG_C_READ_AUDIO_FILES_START          50710
#define RSID_STR_MSG_C_READ_AUDIO_FILES_END            50711
#define RSID_STR_MSG_C_MIXIN_WAVES_START               50712
#define RSID_STR_MSG_C_MIXIN_WAVES_END                 50713
#define RSID_STR_MSG_C_AFFECT_WAVE_START               50714
#define RSID_STR_MSG_C_AFFECT_WAVE_END                 50715
#define RSID_STR_MSG_C_NORMALIZE_KIND                  50716
#define RSID_STR_MSG_C_NORMALIZE_RATIO                 50717
#define RSID_STR_MSG_C_OUTPUT_TO_FILE_START            50718
#define RSID_STR_MSG_C_OUTPUT_TO_FILE_END              50719
#define RSID_STR_MSG_C_OUTPUT_FILE                     50720
#define RSID_STR_MSG_C_OUTPUT_TO_FILE_NO_OUTPUT_NOTICE 50721
#define RSID_STR_MSG_C_OUTPUT_TO_FILE_NO_OUTPUT_END    50722
#define RSID_STR_MSG_C_PROCESSING_TIME                 50723
